由上而下列
由左而右欄

In [1]:
import numpy as np
array=np.arange(1,10).reshape((3,3))
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
int(array[0,0])
int(array[2,2])

9

In [3]:
display(array)
array[:2,1:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[2, 3],
       [5, 6]])

In [8]:
display(array)
display(array[2])        
display(array[2,:])
display(array[:2,1:])           # ":" 就是一個 [ : ) 的觀念，


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([7, 8, 9])

array([7, 8, 9])

array([[2, 3],
       [5, 6]])